name: Direct C++ Code Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Windows x64 Saf C++ Derleme
    runs-on: windows-latest

    steps:
    - name: Kodlari Cek
      uses: actions/checkout@v4

    # Sanal makinedeki hazır paket yöneticisi ile hem Lua'yı hem Sol2'yi tek komutla kuruyoruz
    - name: vcpkg ile Sol2 ve Lua Kur
      run: |
        vcpkg install sol2:x64-windows

    - name: Geliştirici Komut Satırını Aç (Developer Command Prompt)
      uses: ilammy/msvc-dev-cmd@v1

    # vcpkg klasör yollarını derleyiciye (cl.exe) otomatik olarak tanıtıyoruz
    - name: main.cpp Kodunu Derle
      run: |
        cl.exe /EHsc /O2 /I"C:/vcpkg/installed/x64-windows/include" main.cpp /link /LIBPATH:"C:/vcpkg/installed/x64-windows/lib" /SUBSYSTEM:WINDOWS wininet.lib user32.lib gdi32.lib
        
    - name: Derlenen EXE Dosyasini Teslim Et (Artifact)
      uses: actions/upload-artifact@v4
      with:
        name: CS2-Secure-AI-Executor
        path: main.exe
        
